name: Android CI/CD

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 11 for Android
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'

      # Cache Gradle dependencies to speed up the build
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Build the Android app
      - name: Build with Gradle
        run: ./gradlew assembleRelease

      # Setup Ruby and Fastlane
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install Fastlane
        run: gem install fastlane

      # Decode and save Play Store JSON key from secret
      - name: Set up Play Store JSON key
        run: echo "${{ secrets.PLAY_STORE_JSON_KEY }}" > $HOME/playstore_key.json

      # Run Fastlane to upload APK to the Play Store
      - name: Deploy to Google Play
        run: fastlane upload_to_play_store
        env:
          GOOGLE_PLAY_KEY: $HOME/playstore_key.json
          PLAY_STORE_PACKAGE_NAME: ${{ secrets.PLAY_STORE_PACKAGE_NAME }}